version: 2
updates:
  # Only patch lockfile bumps for examples, starter kits, interactive tutorial
  # Only for `dependencies` in `package.json`, `devDependencies` is excluded
  - package-ecosystem: "npm"
    directories:
      - "/examples/**"
      - "/starter-kits/**"
      - "/tutorial/**"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    versioning-strategy: lockfile-only

  # Default behavior elsewhere
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
