name: Deploy examples to Vercel

on:
  push:
    branches:
      - examples

jobs:
  deploy-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy examples
        run: |
          echo Triggering deployment for javascript-live-cursors
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_A5vQXedLkkDRoXn25aDJzIQ9yIrJ/jqSr8qZblN; echo

          echo Triggering deployment for javascript-todo-list
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_ZP3yrtKpROQBi28WVLIlCkSnpZZr/ljMl0CxRJj; echo

          echo Triggering deployment for nextjs-3d-builder
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_ODKBX4EuSUo19sF7UcUUEUjULL50/ur6dsTOSvu; echo

          echo Triggering deployment for nextjs-ai-app-builder
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_5PbrFsltmp5BKHnsBMAAHuJsj3lc/KiSCa1m4tB; echo

          echo Triggering deployment for nextjs-ai-calendar
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_H7bFg3Aslr8x4sOrwDTNwY4pPUvH/7lC9fUdumy; echo

          echo Triggering deployment for nextjs-ai-dashboard-reports
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_4sGozV6komE0oZ3pLCfmq2BmsKHQ/6JL2UE6nNU; echo

          echo Triggering deployment for nextjs-ai-chats
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_s3I6El0fFejHHo1mKmdmZwszO1Ez/Rp1uaVialk; echo

          echo Triggering deployment for nextjs-ai-popup
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_Dej5iVX3gTDoMyl4Zz7eQCeanbTL/ApOZUtheJg; echo

          echo Triggering deployment for nextjs-ai-support
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_EzObSh8qN6zbbRrIHTcjqtRZ5vre/TjSG9uidvC; echo

          echo Triggering deployment for nextjs-blocknote
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_3XoFyLmK5Gtx5twKRTGWFV0jcaUo/1u7c9EF5UX; echo

          echo Triggering deployment for nextjs-comments
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_n44ypzbdWsirLcq3ZSSJ1wLoCAjQ/QWFQY2wKrB; echo

          echo Triggering deployment for nextjs-comments-ai
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_3ywNY3BnasLn51n9GRlUDp65tpo6/TTkfwrbB0X; echo

          echo Triggering deployment for nextjs-comments-audio
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_AdEtQAhkqzpjbOCsytmEnn0j5Myk/bRf48jIuij; echo

          echo Triggering deployment for nextjs-comments-canvas
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_yFy3klLqgmfMNMZI6FVhBj5w5UIl/hS0RaUAXGw; echo

          echo Triggering deployment for nextjs-comments-emails-resend
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_Ht9CiMBXOz7fYMoPGvW0BiSXDeJa/zjNQ0VUNX6; echo

          echo Triggering deployment for nextjs-comments-notifications
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_NeiWF6wVsvMmaLaje9MfWNelU0Ms/HU8HBQCHF4; echo

          echo Triggering deployment for nextjs-comments-overlay
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_LwCaGAgAjY4cQKgazJF0l38xc5IC/Z6s0Rc3TWt; echo

          echo Triggering deployment for nextjs-comments-primitives
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_OEUy8nEYDuKAfOtVKyNy4w3mxoFb/FtJGZAxTFm; echo

          echo Triggering deployment for nextjs-comments-search
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_Spr2FA4X6qq9AVT072XA6RbpOndc/h4fqsUj4Il; echo

          echo Triggering deployment for nextjs-comments-tiptap
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_uNQF4JRW3CMnoA08UWmLfSVVev5K/NusDhfUIma; echo

          echo Triggering deployment for nextjs-comments-video
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_YDCzkYdyvDEXwvvPv9FISlnk1Hcb/YFAwGcgRpb; echo

          echo Triggering deployment for nextjs-connection-status
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_JaA1FylXiIZm6W5hOpGl4OKGmILD/IcdA9I7NKF; echo

          echo Triggering deployment for nextjs-dashboard
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_huuoeSxbMYvNmqcu9UYBUVfP8Cuh/JObDpsWO1x; echo

          echo Triggering deployment for nextjs-form
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_tkr9dMtcFdxzbrZeo0CFzgsqptKI/CTlpFDvYqB; echo

          echo Triggering deployment for nextjs-lexical
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_qeKoPfUCRuI6jvBqV556q8V29YtA/IpvamWQh6G; echo

          echo Triggering deployment for nextjs-lexical-emails-resend
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_ty91zX0hZ71c1KmNKGyT3iGSP4Wr/SbFf4Ans0B; echo

          echo Triggering deployment for nextjs-linear-like-issue-tracker
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_ilOh5HbvxiAu723gnCAMBksCr3CH/3tTZc8ffgM; echo

          echo Triggering deployment for nextjs-live-avatars
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_Lm3c8dWsj390sgIDzemHZTZkuIl0/YtDJP3KyCH; echo

          echo Triggering deployment for nextjs-live-avatars-advanced
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_uqgCWnaIoIjPtAtjLwX2OXK8ZZZu/7dSNgWrdAe; echo

          echo Triggering deployment for nextjs-live-cursors
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_VFNTCXNntCNRR7seoVoJzIY9rpVu/HsfTgB1RmU; echo

          echo Triggering deployment for nextjs-live-cursors-advanced
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_KWcAiPjoXO7R7kiogQ9FxwldLgPC/OSUy6AtimD; echo

          echo Triggering deployment for nextjs-live-cursors-chat
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_C1uUpALDn981xDt4d6dW4N3NAgSn/q5GuDD6b3F; echo

          echo Triggering deployment for nextjs-live-cursors-scroll
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_OEGkIIwL7DwE86gdIBGuEtPPiJXt/CwBOCEdH9f; echo

          echo Triggering deployment for nextjs-live-form-selection
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_ypmCK9Ww5ROey9Y9f1Q4SWtlGSGa/TqtsylS5TE; echo

          echo Triggering deployment for nextjs-notifications-custom
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_3MVsF7dPIZBQdUpfzQjVvZ1dBmPp/x1sO6CecOJ; echo

          echo Triggering deployment for nextjs-notification-settings
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_7B4Yq0uUx6AUog07rLG6VFc5R7O4/Xw8EbvIqRl; echo

          echo Triggering deployment for nextjs-notion-like-ai-editor
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_xvFy7XWt32Yz7gkigfCRZL6AeIBH/J4jKuBvLo8; echo

          echo Triggering deployment for nextjs-spreadsheet-advanced
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_ZJK9PEfgkfsqKRVjxFzwQgAVsdsF/gKp8sJ1f1c; echo

          echo Triggering deployment for nextjs-tiptap
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_LhH3Ag7MdSKWGicQRRIZRHMCacrm/cCpeyZEfFF; echo

          echo Triggering deployment for nextjs-tiptap-advanced
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_J8TT5NanEfJYgWrASs0hqsR6nGa3/QPgzsSe4NF; echo

          echo Triggering deployment for nextjs-tiptap-emails-resend
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_HmPx17FgTo7OY0XkBYnAzttKGm5R/kEYZ6eqhsA; echo

          echo Triggering deployment for nextjs-tiptap-novel
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_uoZ7A0CmwcswPxUqnCy51ds0GXaA/0W5pGVEbOJ; echo

          echo Triggering deployment for nextjs-tldraw-storage
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_mKM14iPdQfC3jH6jQhCKtBoasxQY/0AfEGfHLws; echo

          echo Triggering deployment for nextjs-tldraw-yjs
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_g3L0m4dKUJ54aupCSjto2tNRjGD1/dH39Y2ZydF; echo

          echo Triggering deployment for nextjs-todo-list
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_IzfUkw9eZuOyiS7LbvftjAo812Yk/KvR90vWuGh; echo

          echo Triggering deployment for nextjs-whiteboard
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_8ajcJugNQqYEpbByuanKRMG20qfE/FBiqA6h5pQ; echo

          echo Triggering deployment for nextjs-whiteboard-advanced
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_IxnlQqkzTmSTo2SMguCk2iqNLHmF/nMcl52zGt5; echo

          echo Triggering deployment for nextjs-yjs-blocknote
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_fQZoOjz9J4hUECqmfeagxTqbnM8a/hgBDUVqoWk; echo

          echo Triggering deployment for nextjs-yjs-blocknote-advanced
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_4871V5J1xQFbHpHNrW7sHKljG8jg/9WLrsQpDAC; echo

          echo Triggering deployment for nextjs-yjs-codemirror
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_ar193ztshjapig1WBkx6tI84LMKc/Fhcsf6zY1W; echo

          echo Triggering deployment for nextjs-yjs-lexical
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_Aj8eleVtr87Ti3VThbCcN7BlWBlR/lAf8xuDrHe; echo

          echo Triggering deployment for nextjs-yjs-monaco
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_v3fs0BsdvSSJAngAAJksxgtDgIPl/XZwYVurNTa; echo

          echo Triggering deployment for nextjs-yjs-quill
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_7VVetMjPBMXmjdDBEKZwLhPebtb4/ohpQw8uQmL; echo

          echo Triggering deployment for nextjs-yjs-slate
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_N5cFn4z7l5eXsFsEVltEfmeEkw4U/OvuxtPuMwX; echo

          echo Triggering deployment for nextjs-yjs-tiptap
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_y3mEp1yQYraCLNghy7NcFcj5CPuS/JKf0W69EpG; echo

          echo Triggering deployment for nextjs-tiptap-advanced
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_pCx1U7T80v9b2YS1JURFTFwOBjTe/PlnhiDwwts; echo

          echo Triggering deployment for nuxtjs-live-avatars
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_Nllvun9QgiQBCJ7c3IsSWGaoKJal/CxeQJ87PPy; echo

          echo Triggering deployment for react-comments
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_rnbD5HF80k73CsB7SAzV3dulVM7w/xwSHSZXWKj; echo

          echo Triggering deployment for redux-todo-list
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_HQUymrdvTTH3xHSKEFHGqEdJ2vbU/BbsZfie9sI; echo

          echo Triggering deployment for redux-whiteboard
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_NGEH088LyAT9ARzfmK1UyHqsoPE6/uUD6nb9gge; echo

          echo Triggering deployment for solidjs-live-avatars
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_b1O3o8KWkWufE5ai0nlXc0mDWYex/BdeXq4Cgt0; echo

          echo Triggering deployment for solidjs-live-cursors
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_bNbOiIWwW44BNUKFl2lFQkLpunW9/ud5wK9XAjA; echo

          echo Triggering deployment for sveltekit-live-avatars
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_4yAnK5mBNzVWlpimXtuRbaBcCMLc/oLMPcVmZhs; echo

          echo Triggering deployment for sveltekit-live-cursors
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_Y3BCR3v3QXStJuebeYgpshjZbbEH/ZiYtJflUEJ; echo

          echo Triggering deployment for vuejs-live-avatars
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_ZKJRVnkg5oDCXNVsXHA5cx9GHXSK/sG5t7SlZfZ; echo

          echo Triggering deployment for vuejs-live-cursors
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_hy7iXLmWo1okV1dgr2OrMCn9JMWt/t7E6OY5oIX; echo

          echo Triggering deployment for zustand-flowchart
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_pASCvZXKn5uwLtBt0UrstPs4VwDx/yB1yWVTEYs; echo

          echo Triggering deployment for zustand-todo-list
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_YJIYYvzKUnVTmDsf0qASayLp7qqh/sNDHSdAMku; echo

          echo Triggering deployment for zustand-whiteboard
          curl -s -X POST https://api.vercel.com/v1/integrations/deploy/prj_M8kqqkMZTxXnJGiyKq20DM3gN3Yu/3ZHygiKve8; echo
