name: Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        pkg:
          [
            "liveblocks-client",
            "liveblocks-react",
            "liveblocks-redux",
            "liveblocks-zustand",
            "liveblocks-node",
          ]

    defaults:
      run:
        working-directory: packages/${{ matrix.pkg }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies (and link to local Liveblocks source)
        run: ../../scripts/link-liveblocks.sh

      - name: TypeScript
        run: tsc --noEmit

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm run test-ci

      - name: Run lint checks
        run: npm run lint

  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    timeout-minutes: 60

    env:
      LIVEBLOCKS_SECRET_KEY: ${{ secrets.E2E_TEST_LIVEBLOCKS_SECRET_KEY }}
      LIVEBLOCKS_SERVER: ${{ secrets.E2E_TEST_LIVEBLOCKS_SERVER }}
      LIVEBLOCKS_AUTHORIZE_ENDPOINT: ${{ secrets.E2E_TEST_LIVEBLOCKS_AUTHORIZE_ENDPOINT }}

    defaults:
      run:
        working-directory: e2e/next-sandbox

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies (and link to local Liveblocks source)
        run: ../../scripts/link-liveblocks.sh

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: e2e/next-sandbox/playwright-report
          retention-days: 14
